docs/reference/classes.md
* We have had discussion and made decisions that need to be reflected in the Class Diagram
* https://mitlibraries.atlassian.net/browse/ENGX-231
* Batch Class is removed (and batch_id is removed from Search)
* Rename Search to SearchEvent
* Add source to SearchEvent
* Move search_phrase to Term
* Remove list_unique_terms() from Term
* Relationship between Term and SearchEvent is 1:many
=> Updates TACOS Class diagram

.github/dependabot.yml, .github/workflows/mit-libraries-ruby-ci.yml, .gitignore, Gemfile, Gemfile.lock, app/models/application_record.rb, app/models/search_event.rb, app/models/term.rb, db/migrate/20231019183700_create_terms.rb, db/migrate/20231019191933_create_search_events.rb, db/schema.rb, test/application_system_test_case.rb, test/channels/application_cable/connection_test.rb, test/fixtures/search_events.yml, test/fixtures/terms.yml, test/models/search_event_test.rb, test/models/term_test.rb, test/test_helper.rb
* this implements the first two models and will enable the storage of
the data necessary to get started with this application
* https://mitlibraries.atlassian.net/browse/ENGX-232
https://mitlibraries.atlassian.net/browse/ENGX-233
* Rails
- some of our typical developer gems, rubocop and annotate were added
- rubocop was used to autoformat everything in the `/app` and `/test`
directories
- adds our standard CI setup
- adds dependabot weekly checks
=> Adds Searchevent and term

Gemfile, Gemfile.lock, app/controllers/graphql_controller.rb, app/graphql/mutations/base_mutation.rb, app/graphql/tacos_schema.rb, app/graphql/types/base_argument.rb, app/graphql/types/base_connection.rb, app/graphql/types/base_edge.rb, app/graphql/types/base_enum.rb, app/graphql/types/base_field.rb, app/graphql/types/base_input_object.rb, app/graphql/types/base_interface.rb, app/graphql/types/base_object.rb, app/graphql/types/base_scalar.rb, app/graphql/types/base_union.rb, app/graphql/types/mutation_type.rb, app/graphql/types/node_type.rb, app/graphql/types/query_type.rb, app/graphql/types/search_event_type.rb, config/routes.rb, test/controllers/graphql_controller_test.rb
We need a GraphQL interface to record SearchEvents from TACOS
consumers.
https://mitlibraries.atlassian.net/browse/ENGX-234
* Adds the GraphQL gem and generates a new install.
* Adds a SearchEvent type and corresponding query field that
returns information about the search event and creates a new
SearchEvent (and Term, if applicable).
* Removed a couple of generated GraphQL test fields.
* Miscellaneous rubocop fixes.
=> Initial GraphQL implementation

app/graphql/types/query_type.rb, app/graphql/types/search_event_type.rb, app/graphql/types/standard_identifiers_type.rb, app/graphql/types/term_type.rb, app/models/standard_identifiers.rb, docs/reference/pattern_detection_and_enhancement.md, test/controllers/graphql_controller_test.rb, test/models/standard_identifiers_test.rb
Adds detection and return of detected ISSN, ISBN, DOI, PMID if requested via GraphQL
If the field is not requested via GraphQL, we do not do the detection.
Not included at this time is external lookups to return additional information, but we may want to discuss how that would work as part of this to ensure that need fits in cleanly with this GraphQL design
* Adds support for lookupTerm to be able to query without logging an event
* Adds `phrase` to SearchEventType even though it is technically part of the TermType for convenience
* https://mitlibraries.atlassian.net/browse/ENGX-242
* https://mitlibraries.atlassian.net/browse/ENGX-241
=> Engx242 identifierpatterns

.env.test, .gitignore, Gemfile, Gemfile.lock, README.md, app/graphql/types/details_type.rb, app/graphql/types/standard_identifiers_type.rb, app/models/lookup_doi.rb, app/models/lookup_isbn.rb, app/models/lookup_issn.rb, app/models/lookup_pmid.rb, test/controllers/graphql_controller_test.rb, test/models/lookup_doi_test.rb, test/models/lookup_isbn_test.rb, test/models/lookup_issn_test.rb, test/models/lookup_pmid_test.rb, test/test_helper.rb, test/vcr_cassettes/doi_10_1038/d41586-023-03497-2.yml, test/vcr_cassettes/doi_not_found.yml, test/vcr_cassettes/isbn_978-0-08-102133-0.yml, test/vcr_cassettes/isbn_not_found.yml, test/vcr_cassettes/issn_1078-8956.yml, test/vcr_cassettes/issn_not_found.yml, test/vcr_cassettes/pmid_37953305.yml, test/vcr_cassettes/pmid_not_found.yml, test/vcr_cassettes/searchevent_10_1038/nphys1170.yml
* The ability to provide additional details about what TACOS can detect will allow consuming systems to act on that information. That may mean simply displaying it, or it may mean modifying queries to other systems in more nuanced ways than the original raw search from the user may have led to
* https://mitlibraries.atlassian.net/browse/ENGX-244
* This brings the Fact lookup models over from TIMDEX UI and modifies them slightly to be more useful to this application.
* A details section has been added under standard_identifiers in graphql that will trigger lookups if identifiers have been detected.
* Only lookups that have matches are run, and only if a user has requested details be provided by …
=> Adds data lookup for detected standard identifiers

Gemfile, Gemfile.lock, Procfile, app.json
We need a Procfile and app.json for our Heroku config.
https://mitlibraries.atlassian.net/browse/ENGX-239
This adds a Procfile and app.json with the initial settings we'll
need.
None.
=> Add Heroku config

Gemfile, Gemfile.lock, README.md, app/views/layouts/_site_nav.html.erb
The GDT project added a feature to the theme gem to conditionally include the platform name in the header if the `PLATFORM_NAME` environment variable is supplied.
https://mitlibraries.atlassian.net/browse/GDT-124
This updates the theme gem to the v1.2 tag, which includes the new feature, and documents the PLATFORM_NAME variable.
None. The app will continue to use the standard header if PLATFORM_NAME is not supplied.
=> Update theme gem and document PLATFORM_NAME variable

docs/architecture-decisions/0005-use-multiple-minimal-historical-analytics-models.md
* There are multiple ways we can address this problem
* Using an ADR to provide context and options, gathering feedback on the proposed solution, and then merging the decision allows us to see what else we considered in addition to what we eventually implement.
https://mitlibraries.atlassian.net/browse/TCO-16
=> Adds ADR for historical analytics approach

.gitignore, .yardopts, Gemfile, Gemfile.lock, Makefile, README.md
- adds makefile with useful development commands
- adds `yard` gem and documentation on how to run the local server
`yard` is not perfect, but the value add is enough to include it at this time while we consider if this is a tool we want to use (either as-is or with modified templates)
https://mitlibraries.atlassian.net/browse/TCO-36
=> Adds yard and makefile with development commands

docs/architecture-decisions/0005-use-cancancan-for-authorization.md
We will need authorization in TACOS for the staff UI, which first requires us to choose an authorization gem.
* [TCO-30](https://mitlibraries.atlassian.net/browse/TCO-30)
This adds an ADR to select an authorization gem from among CanCanCan, Pundit, and Action Policy.
The decision we make will affect how we implement authorization.
[TCO-30]: https://mitlibraries.atlassian.net/browse/TCO-30?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add ADR to select an authorization gem

lib/tasks/search_event_loader.rake
https://mitlibraries.atlassian.net/browse/TCO-35
This loader is not meant to be used in production, but instead be a convenience for loading data into development environments to allow for easier development of detection algorithms or reporting.
There is a Dataclip that exports data in the expected format, but it is also easy to generate your own file as it is just `term` and `timestamp` that is expected.
Currently, `source` is provided via CLI but if we find it would be better to include the source in the CSV that would be an easy change to make.
=> Adds CSV loader for SearchEvents

app/models/standard_identifiers.rb, test/models/standard_identifiers_test.rb
NOTE: PMID detection may be entirely silly based on our current bento derived search corpus, but I'd like to keep it in for now as once we expand beyond Bento we may find people search differently.
* The regex was missing PMIDs with no space between the `PMID:` and the indentifier, such as `PMID:35648703`
* https://mitlibraries.atlassian.net/browse/TCO-42
* Updates regex to allow, but not require, a single whitespace character between `pmid:` and the indentifier
=> Updates PMID detection regex

docs/architecture-decisions/0006-use-cancancan-for-authorization.md, docs/architecture-decisions/0007-use-devise-for-authentication.md
We will need authentication in TACOS for the staff UI.
* [TCO-28](https://mitlibraries.atlassian.net/browse/TCO-28)
This adds an ADR to select an authentication approach from among Devise, Clearance, Sorcery, AuthLogic, and a custom solution using built-in Rails security features.
The decision we make will affect how we implement authentication.
[TCO-28]: https://mitlibraries.atlassian.net/browse/TCO-28?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add ADR to select an authentication approach

docs/architecture-decisions/0008-choose-administrative-ui-strategy.md
We need to decide how the application will handle content administration for its internal records. This includes both the records that will be created and managed within the app (fingerprinted phrases for hints, categorization notes), as well as - potentially - records received and stored for use (search terms, imported journal titles, etc).
* [TCO-37](https://mitlibraries.atlassian.net/browse/TCO-37)
This adds an architecture decision record to survey the available gems for content administration, and proposes a choice for how to proceed (to use Administrate for our initial use cases, but a bias towards leaving it behind rather than heavily customizing it as our needs become clearer).
This decision might be a bit unorthodox, as it includes the choice to change implementations. That …
=> Add an ADR for how we approach the administrative interface

app/models/detector.rb, app/models/detector/journal.rb, db/migrate/20240701205444_create_detector_journals.rb, db/schema.rb, test/fixtures/detector/journals.yml, test/models/detector/journal_test.rb
* Storing journal information locally will be used for detecting journal names in incoming search terms
* https://mitlibraries.atlassian.net/browse/TCO-38
* Creates ActiveRecord model Journal inside a new Detector namespace
* It is likely we will move StandardIdentifers into the Detector namespace along with any new Detectors (Hints, etc)
* The `partial_term_match` algorithm may be unwieldy once a large number of journals are loaded. We'll need to assess once we do that whether this can be wired in as part of live matching or just as an interesting data point to help us understand if this would be useful for live detections
* The GraphQL endpoints will …
=> Adds Detector::Journal class

app/models/metrics/algorithms.rb, db/migrate/20240723202204_add_journal_exact_to_metrics_algorithm.rb, db/schema.rb, test/fixtures/search_events.yml, test/fixtures/terms.yml, test/models/detector/journal_test.rb, test/models/metrics/algorithms_test.rb
* Understanding our ability to detect search intent over time is core to our ability to know how we are doing
* https://mitlibraries.atlassian.net/browse/TCO-54
* Adds new field to track exact journal matches to Metrics::Algorithms
* Updates Metrics::Algorithms to run journal exact matches in addition to the existing StandardIdentifer matches. This included a refactor to better support multiple match types.
Journal exact matching is not guaranteed to be an indicator of user search intent because Journal names are also common words in many cases. When we build our our validation workflows, we'll be able to understand what percentage of these types of …
=> Adds exact journal matches to historical analysis

Gemfile, Gemfile.lock, README.md, app/controllers/application_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/models/concerns/fake_auth_config.rb, app/models/user.rb, app/views/layouts/_site_nav.html.erb, config/initializers/_fake_auth_configuration.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20240715190838_devise_create_users.rb, db/schema.rb, test/fixtures/users.yml, test/integration/authentication_test.rb, test/models/fake_auth_test.rb, test/models/user_test.rb, test/test_helper.rb
This adds Touchstone authentication via Devise and Omniauth, along with fake auth for local development and PR builds. The initial auth setup and the fake auth config are in separate commits for ease of review. Please check each commit message for more detailed info on the changesets.
For the time being, I've opted to use Omniauth developer mode for fake auth. We might benefit from using Keycloak in local dev to better simulate a real authentication flow, but setting that proved somewhat complicated and is probably best saved for another time. I've created [a spike ticket](https://mitlibraries.atlassian.net/browse/TCO-59) to investigate further.
To confirm functionality:
* Fake auth logic can be tested in this PR app and locally. It's best to confirm both, because the logic that triggers …
=> Implement authentication

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/ability.rb, app/models/user.rb, db/migrate/20240805203949_add_admin_to_users.rb, db/schema.rb, test/fixtures/users.yml, test/models/user_test.rb
We will need authorization for TACOS, as it will contain a variety of features that should not be avilable to every user.
* https://mitlibraries.atlassian.net/browse/TCO-31
This adds the CanCanCan gem, which [we agreed to use for authorization'](https://github.com/MITLibraries/tacos/blob/main/docs/architecture-decisions/0006-use-cancancan-for-authorization.md). It also introduces a very rudimentary Ability model -- mostly a placeholder until we know what we need -- and a boolean `admin` field to the User model.
It does not implement any rules in the Ability model beyond 'admins can manage anything.'' I debated whether to go even that far, as there's nothing yet to manage.
It's also worth noting that while I was initially opposed to the admin boolean, it does appear to be an idiom within …
=> Add CanCanCan for authorization

app.json
Bumps heroku stack from 22 to 24. I've tested the build process and GraphQL playground and haven't noticed any issues.
https://mitlibraries.atlassian.net/browse/TCO-47
YES dependencies are updated (sort of -- Heroku stack)
=> Upgrade heroku stack to 24

app/models/detector/suggested_resource.rb, app/models/metrics/algorithms.rb, db/migrate/20240813181057_add_suggested_resource_exact_to_metrics_algorithm.rb, db/schema.rb, test/fixtures/detector/suggested_resources.yml, test/fixtures/search_events.yml, test/fixtures/terms.yml, test/models/detector/suggested_resource_test.rb, test/models/metrics/algorithms_test.rb
This extends the `Metrics::Algorithms` model which generates historical records of the application's performance to include matches on the SuggestedResources records that have been added recently. A part of this work is that the `Detector::SuggestedResource` model now gets a `full_term_match` method, which is the crucial link to allow the model to do anything about search traffic.
Along the way the `calculate_fingerprint` method becomes a class method, rather than an instance method. It is still part of the SuggestedResource model, and not in a helper.
Much of this approach has been copied from the Journal title matching work - which seems like a reasonable starting point, both because the uses are similar and because consistent approaches in the app feels like Doing This Right. …
=> Extend Metrics::Algorithms feature to include Detector::SuggestedResource matches

test/fixtures/terms.yml, test/models/metrics/algorithms_test.rb
Some of our search traffic may meet conditions of multiple detections. We need our reports to correctly count these events in all relevant categories.
This starts by creating a single term fixture that should trigger more than one detector - a citation which includes both a DOI and PubMedID for an article.
A new test is also created, which generates a report based only on a search for this term, which asserts that two different counters should have non-zero numbers.
It is a bit awkward to have too many tests that start by deleting existing records from our fixtures - but we're not yet at the point where we'd need something like a factory. We'll talk about that at some point if the need more clearly arises.
https://mitlibraries.atlassian.net/browse/TCO-43
all issues introduced by these …
=> Test for searches with multiple detections

app/graphql/types/detectors_type.rb, app/graphql/types/suggested_resources_type.rb, test/controllers/graphql_controller_test.rb
We have a `SuggestedResource` detector that is not yet modeled in our GraphQL.
* [TCO-24](https://mitlibraries.atlassian.net/browse/TCO-24)
This adds a `SuggestedResourcesType` as a field on `DetectorsType`.
None.
https://mitlibraries.atlassian.net/browse/TCO-###
[TCO-24]: https://mitlibraries.atlassian.net/browse/TCO-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add GraphQL for Detector::SuggestedResource

lib/tasks/search_event_loader.rake, test/tasks/search_event_loader_rake_test.rb, test/vcr_cassettes/search_events_url_loader_from_remote_csv.yml
The initial development for this was a quick prototype to prepare for a demonstration within EngX. However, during our discussion it seems like this might be a good feature to develop further and land for real.
This adds a `search_events:url_loader` task that is based on the existing `search_events:csv_loader` task, with a bit of tweaking from `suggested_resources:reload` for dealing with remote URLs.
More details, including a discussion of a side effect, are in the commit message.
None
=> Add temporary url_loader for search events

app/dashboards/detector/suggested_resource_dashboard.rb, app/models/category.rb, app/models/detector.rb, app/models/detector/journal.rb, app/models/detector/standard_identifiers.rb, app/models/detector/suggested_resource.rb, app/models/detector_category.rb, db/migrate/20240909183413_create_categories.rb, db/migrate/20240909183513_create_detectors.rb, db/migrate/20240909183613_create_detector_categories.rb, db/schema.rb, db/seeds.rb, test/fixtures/categories.yml, test/fixtures/detector_categories.yml, test/fixtures/detectors.yml, test/models/category_test.rb, test/models/detector/journal_test.rb, test/models/detector/standard_identifiers_test.rb, test/models/detector/suggested_resource_test.rb, test/models/detector_test.rb
This adds models for Detector, Category, and the linking DetectorCategory. There are uniqueness and dependency constraints specified in the migration and class files, and confirmed via tests.
I did not write tests for the linking class, as I'm not sure there's a need? I'm happy to write these if desired, though.
The fixtures for these classes match what we've already implemented in code, with the thought that these should change slowly enough that we should probably keep the fixtures in sync? I'm not sure about this though.
The biggest side effect is that implementing the Detector class is done by changing the existing module to a class - which forces changes in a handful of other files.
https://mitlibraries.atlassian.net/browse/TCO-82
all issues introduced by these changes have been …
=> Implement Detector, Category, DetectorCategory

app.json
This adds a postdeploy script to `app.json`, so that new PR builds will be properly seeded. The seeding has already been performed manually for staging and prod tiers.
https://mitlibraries.atlassian.net/browse/TCO-82
=> Add seeding command to app.json postdeploy scripts

app/controllers/admin/categories_controller.rb, app/controllers/admin/detector_categories_controller.rb, app/controllers/admin/detectors_controller.rb, app/dashboards/category_dashboard.rb, app/dashboards/detector_category_dashboard.rb, app/dashboards/detector_dashboard.rb, app/models/metrics/algorithms.rb, config/routes.rb, test/models/metrics/algorithms_test.rb
This adds Administrate dashboards to manage records in the Detector, Category, and DetectorCategory classes. The default dashboards have been lightly customized in a second commit to focus on the changes. These are focused on making the records easier to manage without remembering record IDs.
A side effect of this change is updating the annotations for the algorithm classes, which got out of sync somewhere.
https://mitlibraries.atlassian.net/browse/TCO-85
=> Add Detectors, Categories, and DetectorCategories to administrate dashboard

app/controllers/report_controller.rb, app/helpers/metrics_helper.rb, app/models/ability.rb, app/models/metrics/algorithms.rb, app/views/admin/application/_navigation.html.erb, app/views/layouts/_site_nav.html.erb, app/views/report/algorithm_metrics.html.erb, app/views/report/index.html.erb, config/routes.rb, test/controllers/report_controller_test.rb, test/helpers/metrics_helper_test.rb
https://mitlibraries.atlassian.net/browse/TCO-###
=> Tco 19 snapshot dashboard

app/graphql/types/categories_type.rb, app/graphql/types/query_type.rb, app/graphql/types/search_event_type.rb, app/graphql/types/term_type.rb, app/models/categorization.rb, app/models/category.rb, app/models/detection.rb, app/models/term.rb, db/migrate/20240923182249_create_categorization.rb, db/schema.rb, docs/reference/classes.md, test/controllers/graphql_controller_test.rb, test/fixtures/categorizations.yml, test/models/categorization_test.rb, test/models/category_test.rb, test/models/detection_test.rb, test/models/term_test.rb
This finishes the implementation of the Categorization work:
* Builds the method to calculate categorization scores based on which Detections have already been created
* Records those scores in the database for later processing or analysis
* Updates the logSearchEvent GraphQL endpoint to perform the Detection and Categorization work.
* Updates both GraphQL endpoints to return the resulting Categorization information
https://mitlibraries.atlassian.net/browse/TCO-83
YES migrations are included
=> Implement Categorization

app/controllers/admin/categorizations_controller.rb, app/dashboards/categorization_dashboard.rb, app/dashboards/search_event_dashboard.rb, app/models/ability.rb, app/views/layouts/_site_nav.html.erb, config/routes.rb
* Our config was allowing Terms and SearchEvents to be created and
edited in Administrate which is not intended
* It will be convenient to have a mechansim in-app for authenticated
users to look at our Categorizations prior to us building out custom
reports/dashboards
* https://mitlibraries.atlassian.net/browse/TCO-92
* https://mitlibraries.atlassian.net/browse/TCO-93
* Restricts routes which is how Administrate determins which features
to enable
* Terms and SearchEvents cannot be created or edited in Administrate
* This still allows admins to destroy a Term in case we determine it
contains sensitive information. SearchEvents can only be destroyed by
destroying the associated Term and relying on …
=> Categorization dashboard

app/models/categorization.rb, app/models/detection.rb, app/models/detector/journal.rb, app/models/detector/standard_identifiers.rb, app/models/detector/suggested_resource.rb, app/models/term.rb, test/models/categorization_test.rb, test/models/detection_test.rb, test/models/detector/journal_test.rb, test/models/detector/standard_identifiers_test.rb, test/models/detector/suggested_resource_test.rb, test/models/term_test.rb
This patches a bug in the Detection and Categorization workflow, where new records don't adequately respond to changes in the DETECTOR_VERSION value. The solution is to be more explicit about assigning that value from ENV, doing so one step farther upstream rather than inside the Detection and Categorization models themselves.
https://mitlibraries.atlassian.net/browse/TCO-90
=> Patch bug around DETECTOR_VERSION managing new record creation

app/graphql/types/detectors_type.rb, app/models/detector/lcsh.rb, app/models/metrics/algorithms.rb, app/models/term.rb, db/migrate/20241001205152_add_lcsh_to_metrics_algorithm.rb, db/schema.rb, db/seeds.rb, docs/reference/classes.md, test/controllers/graphql_controller_test.rb, test/fixtures/detector_categories.yml, test/fixtures/detectors.yml, test/fixtures/search_events.yml, test/fixtures/terms.yml, test/models/detector/lcsh_test.rb, test/models/metrics/algorithms_test.rb
https://mitlibraries.atlassian.net/browse/TCO-71
YES migrations are included
=> Add LCSH detector

app/models/detector/citation.rb, app/models/detector/lcsh.rb, app/models/detector/pattern_checker.rb, app/models/detector/standard_identifiers.rb, test/models/detector/citation_test.rb, test/models/detector/lcsh_test.rb
Summary of changes (please refer to commit messages for full details):
- updated variable name in many detectors to better reflect we are expecting strings not Term objects
- refactored Citation to use strings and not Term objects to match our other Detectors
https://mitlibraries.atlassian.net/browse/TCO-106
=> Update Detectors to use phrase inputs instead of Terms

Gemfile, Gemfile.lock, app.json, config/puma.rb
* This adds a few additional useful metrics in our heroku dashboard for stage/prod level apps (it doesn't work in eco dynos so pr builds will not collect this data)
* see also: https://devcenter.heroku.com/articles/language-runtime-metrics-ruby
* https://mitlibraries.atlassian.net/browse/TCO-78
* adds barnes gem
* configures puma per heroku docs to enable barnes
* updates app.json to add the metrics collection to PR builds even though they probably won't do anything in our eco dynos
None really, but the only other rails app we do this with is Bento. Other apps should likely get updated to collect this data if we don't see any side effects.
all issues …
=> Adds barnes gem to collect Ruby Language Metrics

app/models/metrics/algorithms.rb, db/migrate/20241011181823_add_citation_to_metrics_algorithms.rb, db/schema.rb, test/fixtures/search_events.yml, test/fixtures/terms.yml, test/models/metrics/algorithms_test.rb
This integrates the citation detector with the monthly metrics setup. It includes a tweak to one of the term fixtures, because the ISBN fixture had ended up getting counted in the citation detector (which is a real phenomenon, but our test fixtures feel like they should be crafted to keep things separate).
The fact that this needed to tweak a different term fixture is an indication that our detectors are starting to overlap. This is a real phenomenon in production, and is expected as we start to build more detectors.
I do not have a notion for now about how to address this in the more constrained test environment, where we can carefully craft fixtures to do exactly what we intend. It feels like this behavior should be confirmed via explicit tests that address this overlap, but the tests …
=> Integrate Citation detector with Metrics

Gemfile, Gemfile.lock, app/controllers/term_controller.rb, app/helpers/application_helper.rb, app/models/ability.rb, app/models/category.rb, app/models/confirmation.rb, app/models/term.rb, app/models/user.rb, app/views/layouts/_site_nav.html.erb, app/views/term/confirm_index.html.erb, app/views/term/confirm_term.html.erb, config/initializers/pagy.rb, config/routes.rb, db/migrate/20241029181747_create_confirmation.rb, db/schema.rb, db/seeds.rb, docs/explanation/categorization-workflow.md, docs/reference/classes.md, test/controllers/term_controller_test.rb, test/fixtures/categories.yml, test/fixtures/confirmations.yml, test/models/category_test.rb, test/models/confirmation_test.rb, test/models/term_test.rb, test/models/user_test.rb
This implements most of the confirmation workflow, wherein users of the application review search terms and provide some ground truth feedback about how they should ideally be categorized by the automated processes.
This PR does not fully implement this workflow, because the UI does not include a working form (and the Term controller has no method to receive that input). However, it gets close enough that the next PR should be able to do so easily. This PR is already verging on too big, so I'd like to ask for review now.
The biggest thing to note here is that this adds a fourth category to the application, for "Undefined". The intent is not for the application to make use of this option during the Categorization workflow, but humans should be given this option in order for the …
=> Simple confirmation workflow

app/graphql/types/query_type.rb, app/models/search_logger.rb, test/models/search_logger_test.rb
* This will simplify logic in GraphQL while making it easier to expand the logic necessary to add more complex logic to preprocess terms for each source or do any other normalization to incoming data.
* Pre-work for: https://mitlibraries.atlassian.net/browse/TCO-113
https://mitlibraries.atlassian.net/browse/TCO-###
=> Create SearchLogger model

Gemfile, Gemfile.lock, README.md, config/initializers/sentry.rb
This adds the Sentry integration, similarly to what we've done with other applications and the current Sentry documentation.
https://mitlibraries.atlassian.net/browse/TCO-88
YES dependencies are updated
=> Add and configure Sentry gem

docs/architecture-decisions/0010-use-single-fingerprint-model.md
We currently use fingerprinting for suggested resources. We are planning to expand this functionality to terms to support clustering, and we also need to refactor suggested resource fingerprinting to accommodate multiple phrases/fingerprints per suggested resource. This felt like a good opportunity to reevaluate our fingerprinting implementation.
* [TCO-74](https://mitlibraries.atlassian.net/browse/TCO-74)
* [Add automatic fingerprinting for Term records (unticketed -- link to PR)](https://github.com/MITLibraries/tacos/pull/138)
This ADR proposes that we add a central `Fingerprint` model, linked to `Terms`, which is leveraged by `SuggestedResource` and any other detectors that require fingerprinting.
EngX had discussed this as a possible approach in a recent meeting. Consensus on this ADR …
=> Introduce ADR for fingerprinting

app/models/preprocessor_primo.rb, app/models/search_logger.rb, test/controllers/graphql_controller_test.rb, test/models/preprocessor_primo_test.rb
* Primo has a more complex keyword search capability than tacos is able to understand
* Rather than adding complexity to what tacos understands to match primo, we are adding a normalization step via source preprocessors
* https://mitlibraries.atlassian.net/browse/TCO-113
* This adds our first source preprocessor to handle incoming searches from primo ui
* It does not yet handle complex searches (targeted field searching or multiple keywords being combined with boolean logic)
* When a complex search is detected, we attach it to a shared term 'unhandled complex primo query' so we can better understand the volume of these more complex queries. This should provide us with some initial data to help us …
=> Adds preprocessor for incoming primo searches

db/migrate/20241204214748_change_column_null_confirmation_category.rb
* https://mitlibraries.atlassian.net/browse/TCO-125
* Creates a Category "Flagged" if one does not already exist before trying to update data based on this specific Category
* This migration has already run and it is normally not a good practice to update migrations to prevent databases from not bein in synch with the migration. In this case, all this does is introduce the code that was run manually in environments where this was run so it is fine and expected that those environments will not run it again.
YES migrations are …
=> Change existing migration to create Category

Gemfile, Gemfile.lock
Brief reversion for SQLite3 back to version 1.7, after running into local issues using 2.4
=> Revert sqlite3 to 1.7

.yardopts, app/models/detector/standard_identifiers.rb, test/models/detector/standard_identifiers_test.rb
* It is not possible to validate detected ISBNs via regex alone
* We are seeing false positives for ISBNs in production that are invalid
* We validate ISSNs, but had not gone back and added this logic to ISBN
* https://mitlibraries.atlassian.net/browse/TCO-114
* Follows the pattern to strip detected ISBNs in a way similar to ISSNs
* Follows the ISBN-10 and ISBN-13 validation specifications
* Updates tests for valid ISBNs are actually using valid ISBNs (previously, the ISBN-10s were incorrect converted to ISBN-13s)
* Adds additional ISBN-13 examples to test positive validations
* Adds additional ISBN-13 examples to test negative validations
* Removed "ISBN: …
=> Validate ISBNs detected via regex

app/models/ability.rb, test/controllers/static_controller_test.rb, test/integration/admin_dashboard_test.rb
* we have users that should have access to term/search event data
* eventually, we will likely create a specific role for that, but for now the user list is so small this is fine
* playground access is also being given, mostly as a convenience in PR builds to not have to manually assign admin permissions to get that feature
* https://mitlibraries.atlassian.net/browse/TCO-133
* Allows read access to Terms/SearchEvents to all authenticated users
* Allows playground access to all authenticated users
* Playground access used without care could log additional searchevents as if they came from a production system that actually came from the playground
Summary of …
=> Authenticated users terms and playground access

app/controllers/term_controller.rb, app/models/ability.rb, app/models/term.rb, app/views/term/unconfirmed.html.erb, test/controllers/term_controller_test.rb, test/models/term_test.rb
The confirmation workflow was predicated on humans providing a second opinion on categorization, allowing us to review how the application is already performing. However, when we initially rolled out this workflow, it allowed humans to provide confirmation on every term in the system, and not just those which the system had categorized.
https://mitlibraries.atlassian.net/browse/tco-126
This adds:
* A categorized scope to the Term model
* Forks the logic in the term controller's "unconfirmed" method, returning two different recordsets. By default it includes only categorized terms (via the scope added above). However, there is a URL parameter to leave this restriction out.
* The template for this list of terms has buttons to switch between the two modes. The default behavior applies the …
=> Add option to confirm only categorized terms

.env.test, README.md, app/graphql/types/details_type.rb, app/graphql/types/standard_identifiers_type.rb, app/models/detector/standard_identifiers.rb, app/models/lookup_barcode.rb, app/models/lookup_isbn.rb, app/models/lookup_libkey.rb, test/models/detector/standard_identifiers_test.rb, test/models/lookup_libkey_test.rb, test/test_helper.rb, test/vcr_cassettes/libkey_doi_10_1038/d41586-023-03497-2.yml, test/vcr_cassettes/libkey_doi_nonsense.yml, test/vcr_cassettes/libkey_pmid_10490598.yml, test/vcr_cassettes/libkey_pmid_nonsense.yml
The PR build has the LibKey ENV all set. If you want to run this locally, grab the 4 values from there. To compare details with the previous doi/pmid lookups I suggest either locally via the ENV or just using staging for the "previous' version.
Separate from this PR will be a decision on whether to default to LibKey. Landing this code does not commit us to using it for both DOI and PMID. That said, I think it is a good option for us or I wouldn't be trying to merge this so keep in mind that I do intend to suggest we convert to this method (at least for staging) very soon.
CodeClimate/rubocop is correct about everything it flagged. I'd like to accept all of that technical debt, but if there is anything you think should be addressed before merge I'm open to it.
Why are these changes being …
=> Add LibKey API option for DOI and PMID metadata

app/assets/stylesheets/application.scss, app/assets/stylesheets/partials/_search.scss, app/controllers/demo_controller.rb, app/controllers/intervention_controller.rb, app/javascript/controllers/content_loader_controller.js, app/javascript/controllers/hello_controller.js, app/javascript/controllers/index.js, app/views/demo/_form.html.erb, app/views/demo/index.html.erb, app/views/demo/view.html.erb, app/views/intervention/doi.html.erb, app/views/layouts/_head.html.erb, config/routes.rb, test/controllers/demo_controller_test.rb, test/controllers/intervention_controller_test.rb
Adds a demo/simulation UI including interventions that could be used in other interfaces, such as bento or timdex-ui.
* https://mitlibraries.atlassian.net/browse/TCO-80
* https://mitlibraries.atlassian.net/browse/TCO-115
* https://mitlibraries.atlassian.net/browse/TCO-121
=> Tco80 simulator

app/views/static/playground.html.erb
4.x recently was released and breaks our GraphiQL playground.
https://mitlibraries.atlassian.net/browse/TCO-166 is tracking how to upgrade to v4
https://mitlibraries.atlassian.net/browse/TCO-###
=> Pin CDN version of GraphiQL to 3.x

renovate.json
* Ruby and Rails should keep versions in line with recommendations
* This pins Ruby to version 3.4.x and Rails to 7.2x
* When we upgrade to Rails 8 we adjust
=> Restrict ruby and rails upgrades

app/assets/stylesheets/application.scss, app/assets/stylesheets/partials/_suggestion-panel.scss, app/views/intervention/doi.html.erb
As we explore interventions to be delivered to interfaces in our ecosystem, we need a consistent design pattern to deliver these interventions and call attention to them.
This work implements a design for a new "Suggestion Panel" component, which can be used for interventions as well as other types of suggestions in our products.
This work is local to TACOS for now, but will be extracted into an official design system component in the future.
Placeholder parts:
* Color variables for the design system are defined in the `_suggestion-panel.scss` file for the time being and need to be extracted.
* The current TACOS Font Awesome version is used as a placeholder. This should be replaced via the CDN / Design system version in …
=> First pass of Suggestion Panel Component - to be later extracted into first design system component.

app/models/detector/ml_citation.rb, test/models/detector/ml_citation_test.rb, test/test_helper.rb, test/vcr_cassettes/lambda_citation.yml, test/vcr_cassettes/lambda_citation_sequence.yml, test/vcr_cassettes/lambda_no_citation.yml, test/vcr_cassettes/lambda_with_wrong_secret.yml
Now that the detector lambda has been deployed and can do real work, it seems like some last-minute tweaks are needed for TACOS to communicate reliably.
Three small tweaks are needed to Detector::MlCitation:
1. Add a Content-Type header to the communication with the detector
2. Sort and re-hash the hash of features (the order of parameters matters for scikit-learn)
3. The response parsing in the fetch method needs to account for a capitalized response "True" instead of "true".
Along with these changes comes a few tweaks around the tests.
- Making sure we explicitly test for both responses via the .new() method
- Setting the sequence test to use its own cassette with multiple interactions (avoids a first-time-through test failure when renegenerating cassettes)
- Scrubbing the challenge …
=> Final integration tweaks with detector lambda

Gemfile, Gemfile.lock, app/models/detector/ml_citation.rb, test/models/detector/ml_citation_test.rb, test/test_helper.rb
This moves the extract_features method in Detector::MlCitation into the initialize method, allowing us to quickly check for whether a given term has enough non-zero features to make it worth calling the detector.
From our analysis in the TACOS notebooks, we believe that phrases which result in only two non-zero values among all their features will never end up being a citation - and that this threshold will allow us to skip the citation detector in 90% of searches.
The filtering is performed in a convenience method named enough_nonzero_values? (naming things is hard).
There is one side effect worth noting: the @detections instance variable is now defined as false at the top of the initialize method, before the first guard clause, so that we get a consistent Boolean value in all …
=> Filter searches before citation detector
